# Generated by Django 6.0 on 2025-12-27 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0010_course_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("name", "user")},
        ),
    ]
