# Generated by Django 6.0 on 2025-12-28 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabooster", "0011_alter_course_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepoint",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="syllabooster.unit",
            ),
        ),
    ]
